/* Full CIBLE ENERGIE rubrique catalogue, extracted from Sage T_RUB (163 lines). */
module.exports = [
{
"code": "1000",
"label": "SALAIRE DE BASE",
"family": "BRUT",
"formula": "Nombre x Base",
"base": "SALJOURN",
"nombre": "NBREJOUT",
"taux": null,
"tauxPat": null,
"cnps": true,
"impo": true,
"sens": "GAIN"
},
{
"code": "1005",
"label": "SALAIRE DE BASE (Horaire)",
"family": "BRUT",
"formula": "Nombre x Base",
"base": "SALHOR",
"nombre": "NBREHEU",
"taux": null,
"tauxPat": null,
"cnps": true,
"impo": true,
"sens": "GAIN"
},
{
"code": "1030",
"label": "SURSALAIRE",
"family": "BRUT",
"formula": "Nombre x Base",
"base": "CL05",
"nombre": "NJOURP",
"taux": null,
"tauxPat": null,
"cnps": true,
"impo": true,
"sens": "GAIN"
},
{
"code": "1040",
"label": "PRIME ANCIENNETE",
"family": "BRUT",
"formula": "Montant pris tel quel",
"base": null,
"nombre": null,
"taux": null,
"tauxPat": null,
"cnps": true,
"impo": true,
"sens": "GAIN"
},
{
"code": "1055",
"label": "ANCIENNETE",
"family": "BRUT",
"formula": "Base x Taux",
"base": "BASEANC",
"nombre": null,
"taux": null,
"tauxPat": null,
"cnps": true,
"impo": true,
"sens": "GAIN"
},
{
"code": "1060",
"label": "ANCIENNETE",
"family": "BRUT",
"formula": "Montant pris tel quel",
"base": null,
"nombre": null,
"taux": null,
"tauxPat": null,
"cnps": true,
"impo": true,
"sens": "GAIN"
},
{
"code": "1065",
"label": "ANCIENNETE ANC",
"family": "BRUT",
"formula": "Nombre x Base x Taux",
"base": "BASEANC",
"nombre": null,
"taux": null,
"tauxPat": null,
"cnps": true,
"impo": true,
"sens": "GAIN"
},
{
"code": "1066",
"label": "Rappel Ancienneté",
"family": "BRUT",
"formula": "Montant pris tel quel",
"base": null,
"nombre": null,
"taux": null,
"tauxPat": null,
"cnps": true,
"impo": true,
"sens": "GAIN"
},
{
"code": "1067",
"label": "JOURS FERIES",
"family": "BRUT",
"formula": "Nombre x Base",
"base": null,
"nombre": "NOMJOUFE",
"taux": null,
"tauxPat": null,
"cnps": true,
"impo": true,
"sens": "GAIN"
},
{
"code": "1068",
"label": "HORAIRES ACCRUS",
"family": "BRUT",
"formula": "Nombre x Base",
"base": "CL11",
"nombre": "NJOURP",
"taux": null,
"tauxPat": null,
"cnps": true,
"impo": true,
"sens": "GAIN"
},
{
"code": "1080",
"label": "FORFAIT H.S.",
"family": "BRUT",
"formula": "Nombre x Base",
"base": "CL18",
"nombre": "NJOURP",
"taux": null,
"tauxPat": null,
"cnps": true,
"impo": true,
"sens": "GAIN"
},
{
"code": "1081",
"label": "FORFAIT HS NT",
"family": "BRUT",
"formula": "Nombre x Base",
"base": "CL18",
"nombre": "NJOURP",
"taux": null,
"tauxPat": null,
"cnps": true,
"impo": true,
"sens": "GAIN"
},
{
"code": "1082",
"label": "FORFAIT H.S.",
"family": "BRUT",
"formula": "Nombre x Base",
"base": "CL11",
"nombre": "NJOURP",
"taux": null,
"tauxPat": null,
"cnps": true,
"impo": true,
"sens": "GAIN"
},
{
"code": "1083",
"label": "HEURES SUP A 20 %",
"family": "BRUT",
"formula": "Nombre x Base x Taux",
"base": "SALHOR1",
"nombre": "NBREHS20",
"taux": 120.0,
"tauxPat": null,
"cnps": true,
"impo": true,
"sens": "GAIN"
},
{
"code": "1084",
"label": "HEURES SUP A 20 %",
"family": "BRUT",
"formula": "Nombre x Base x Taux",
"base": "SALHOR1",
"nombre": "NBREHS20",
"taux": 120.0,
"tauxPat": null,
"cnps": true,
"impo": true,
"sens": "GAIN"
},
{
"code": "1085",
"label": "HEURES SUP A 20 %",
"family": "BRUT",
"formula": "Nombre x Base x Taux",
"base": "SALBHOR",
"nombre": "NBREHS20",
"taux": 120.0,
"tauxPat": null,
"cnps": true,
"impo": true,
"sens": "GAIN"
},
{
"code": "1086",
"label": "HEURES SUP A 20 %",
"family": "BRUT",
"formula": "Nombre x Base x Taux",
"base": "CONWILL",
"nombre": "NBREHS20",
"taux": 120.0,
"tauxPat": null,
"cnps": true,
"impo": true,
"sens": "GAIN"
},
{
"code": "1088",
"label": "HEURES SUP 30 %",
"family": "BRUT",
"formula": "Nombre x Base x Taux",
"base": "SALHOR1",
"nombre": "NBREHSUP30",
"taux": 130.0,
"tauxPat": null,
"cnps": true,
"impo": true,
"sens": "GAIN"
},
{
"code": "1089",
"label": "HEURES SUP 30 %",
"family": "BRUT",
"formula": "Nombre x Base x Taux",
"base": "SALBHOR",
"nombre": "NBREHSUP30",
"taux": 130.0,
"tauxPat": null,
"cnps": true,
"impo": true,
"sens": "GAIN"
},
{
"code": "1090",
"label": "HEURES SUP 30 %",
"family": "BRUT",
"formula": "Nombre x Base x Taux",
"base": "SALHOSCH",
"nombre": "NBREHSUP30",
"taux": 130.0,
"tauxPat": null,
"cnps": true,
"impo": true,
"sens": "GAIN"
},
{
"code": "1091",
"label": "HEURES SUP 30 %",
"family": "BRUT",
"formula": "Nombre x Base x Taux",
"base": "SALBHOR",
"nombre": "NBREHSUP30",
"taux": 130.0,
"tauxPat": null,
"cnps": true,
"impo": true,
"sens": "GAIN"
},
{
"code": "1092",
"label": "HEURES SUP 40 %",
"family": "BRUT",
"formula": "Nombre x Base x Taux",
"base": "SALHOR1",
"nombre": "NBREHS40",
"taux": 140.0,
"tauxPat": null,
"cnps": true,
"impo": true,
"sens": "GAIN"
},
{
"code": "1093",
"label": "HEURES SUP 40 %",
"family": "BRUT",
"formula": "Nombre x Base x Taux",
"base": "SALHOR1",
"nombre": "NBREHS40",
"taux": 140.0,
"tauxPat": null,
"cnps": true,
"impo": true,
"sens": "GAIN"
},
{
"code": "1094",
"label": "HEURES SUP 40 %",
"family": "BRUT",
"formula": "Nombre x Base x Taux",
"base": "SALHOSCH",
"nombre": "NBREHS40",
"taux": 140.0,
"tauxPat": null,
"cnps": true,
"impo": true,
"sens": "GAIN"
},
{
"code": "1095",
"label": "HEURES SUP 40 %",
"family": "BRUT",
"formula": "Nombre x Base x Taux",
"base": "CONWILL",
"nombre": "NBREHS40",
"taux": 140.0,
"tauxPat": null,
"cnps": true,
"impo": true,
"sens": "GAIN"
},
{
"code": "1096",
"label": "HEURES SUP A 50 %",
"family": "BRUT",
"formula": "Nombre x Base x Taux",
"base": "SALHOR1",
"nombre": "NBREHSUP50",
"taux": 150.0,
"tauxPat": null,
"cnps": true,
"impo": true,
"sens": "GAIN"
},
{
"code": "1097",
"label": "HEURES SUP A 50 %",
"family": "BRUT",
"formula": "Nombre x Base x Taux",
"base": "SALBHOR",
"nombre": "NBREHSUP50",
"taux": 150.0,
"tauxPat": null,
"cnps": true,
"impo": true,
"sens": "GAIN"
},
{
"code": "1098",
"label": "HEURES SUP A 50 %",
"family": "BRUT",
"formula": "Nombre x Base x Taux",
"base": "SALHOSCH",
"nombre": "NBREHSUP50",
"taux": 150.0,
"tauxPat": null,
"cnps": true,
"impo": true,
"sens": "GAIN"
},
{
"code": "1099",
"label": "HEURES SUP A 50 %",
"family": "BRUT",
"formula": "Nombre x Base x Taux",
"base": "CONWILL",
"nombre": "NBREHSUP50",
"taux": 150.0,
"tauxPat": null,
"cnps": true,
"impo": true,
"sens": "GAIN"
},
{
"code": "2000",
"label": "HEURES SUP A 100 %",
"family": "BRUT",
"formula": "Nombre x Base x Taux",
"base": "SALHOR1",
"nombre": "NBREHSU100",
"taux": 200.0,
"tauxPat": null,
"cnps": true,
"impo": true,
"sens": "GAIN"
},
{
"code": "2010",
"label": "Rappel heures suppl à 20 %",
"family": "BRUT",
"formula": "Nombre x Base x Taux",
"base": "SALBHOR",
"nombre": "NBREHS20",
"taux": 120.0,
"tauxPat": null,
"cnps": true,
"impo": true,
"sens": "GAIN"
},
{
"code": "2025",
"label": "Rappel heures suppl à 50 %",
"family": "BRUT",
"formula": "Nombre x Base x Taux",
"base": "SALBHOR",
"nombre": "NBREHSUP50",
"taux": 150.0,
"tauxPat": null,
"cnps": true,
"impo": true,
"sens": "GAIN"
},
{
"code": "2030",
"label": "Rappel heures suppl à 100 %",
"family": "BRUT",
"formula": "Nombre x Base x Taux",
"base": "SALBHOR",
"nombre": "NBREHSU100",
"taux": 200.0,
"tauxPat": null,
"cnps": true,
"impo": true,
"sens": "GAIN"
},
{
"code": "2032",
"label": "SOLDE DE TOUT COMPTE",
"family": "BRUT",
"formula": "Montant pris tel quel",
"base": null,
"nombre": null,
"taux": null,
"tauxPat": null,
"cnps": true,
"impo": true,
"sens": "GAIN"
},
{
"code": "2033",
"label": "RAPPEL HEURES SUP",
"family": "BRUT",
"formula": "Montant pris tel quel",
"base": null,
"nombre": null,
"taux": null,
"tauxPat": null,
"cnps": true,
"impo": true,
"sens": "GAIN"
},
{
"code": "2034",
"label": "RAPPEL PRIME",
"family": "BRUT",
"formula": "Montant pris tel quel",
"base": null,
"nombre": null,
"taux": null,
"tauxPat": null,
"cnps": true,
"impo": true,
"sens": "GAIN"
},
{
"code": "2035",
"label": "RAPPEL SALAIRE",
"family": "BRUT",
"formula": "Montant pris tel quel",
"base": null,
"nombre": null,
"taux": null,
"tauxPat": null,
"cnps": true,
"impo": true,
"sens": "GAIN"
},
{
"code": "2036",
"label": "RAPPEL PRIME MER",
"family": "BRUT",
"formula": "Nombre x Base",
"base": null,
"nombre": "NJOUTRAP",
"taux": null,
"tauxPat": null,
"cnps": true,
"impo": true,
"sens": "GAIN"
},
{
"code": "2037",
"label": "RAPPEL 13ème MOIS",
"family": "BRUT",
"formula": "Montant pris tel quel",
"base": null,
"nombre": null,
"taux": null,
"tauxPat": null,
"cnps": true,
"impo": true,
"sens": "GAIN"
},
{
"code": "2100",
"label": "PRIME D'ASSIDUITE",
"family": "BRUT",
"formula": "Nombre x Base",
"base": "CL07",
"nombre": "NJOURP",
"taux": null,
"tauxPat": null,
"cnps": true,
"impo": true,
"sens": "GAIN"
},
{
"code": "2101",
"label": "PRIME D'ASTREINTE",
"family": "BRUT",
"formula": "Nombre x Base",
"base": "CL12",
"nombre": "NJOUTRAP",
"taux": null,
"tauxPat": null,
"cnps": true,
"impo": true,
"sens": "GAIN"
},
{
"code": "2102",
"label": "PRIME DE  RESPONSABILITE UD",
"family": "BRUT",
"formula": "Nombre x Base",
"base": "CL19",
"nombre": "NJOURP",
"taux": null,
"tauxPat": null,
"cnps": true,
"impo": true,
"sens": "GAIN"
},
{
"code": "2103",
"label": "PRIME DE  RISQUE",
"family": "BRUT",
"formula": "Nombre x Base",
"base": "CL09",
"nombre": "NJOURP",
"taux": null,
"tauxPat": null,
"cnps": true,
"impo": true,
"sens": "GAIN"
},
{
"code": "2104",
"label": "PRIME DE BONNE SEPARATION",
"family": "BRUT",
"formula": "Nombre x Base",
"base": null,
"nombre": "NJOUTRAP",
"taux": null,
"tauxPat": null,
"cnps": true,
"impo": true,
"sens": "GAIN"
},
{
"code": "2105",
"label": "PRIME DE CAISSE",
"family": "BRUT",
"formula": "Nombre x Base",
"base": "CL16",
"nombre": "NJOURP",
"taux": null,
"tauxPat": null,
"cnps": true,
"impo": true,
"sens": "GAIN"
},
{
"code": "2106",
"label": "PRIME DE CHANTIER",
"family": "BRUT",
"formula": "Nombre x Base",
"base": "CL10",
"nombre": "NJOURP",
"taux": null,
"tauxPat": null,
"cnps": true,
"impo": true,
"sens": "GAIN"
},
{
"code": "2107",
"label": "PRIME DE CONFIDENTIALITE",
"family": "BRUT",
"formula": "Nombre x Base",
"base": "CL32",
"nombre": "NJOURP",
"taux": null,
"tauxPat": null,
"cnps": true,
"impo": true,
"sens": "GAIN"
},
{
"code": "2108",
"label": "PRIME DE FIN DE CONTRAT",
"family": "BRUT",
"formula": "Nombre x Base",
"base": null,
"nombre": null,
"taux": null,
"tauxPat": null,
"cnps": true,
"impo": true,
"sens": "GAIN"
},
{
"code": "2109",
"label": "PRIME D'EAU",
"family": "BRUT",
"formula": "Nombre x Base",
"base": "CL34",
"nombre": "NJOURP",
"taux": null,
"tauxPat": null,
"cnps": true,
"impo": true,
"sens": "GAIN"
},
{
"code": "2110",
"label": "PRIME DE MAINTENANCE",
"family": "BRUT",
"formula": "Nombre x Base",
"base": null,
"nombre": "NJOUTRAP",
"taux": null,
"tauxPat": null,
"cnps": true,
"impo": true,
"sens": "GAIN"
},
{
"code": "2115",
"label": "PRIME DE MER",
"family": "BRUT",
"formula": "Nombre x Base",
"base": "CL23",
"nombre": "NJOUTRAP",
"taux": null,
"tauxPat": null,
"cnps": true,
"impo": true,
"sens": "GAIN"
},
{
"code": "2116",
"label": "PRIME DE NAISSANCE",
"family": "BRUT",
"formula": "Montant pris tel quel",
"base": null,
"nombre": null,
"taux": null,
"tauxPat": null,
"cnps": true,
"impo": true,
"sens": "GAIN"
},
{
"code": "2117",
"label": "PRIME DE PANIER",
"family": "BRUT",
"formula": "Nombre x Base",
"base": "CL27",
"nombre": "NJOURP",
"taux": null,
"tauxPat": null,
"cnps": true,
"impo": true,
"sens": "GAIN"
},
{
"code": "2118",
"label": "PRIME DE PERFORMANCE",
"family": "BRUT",
"formula": "Nombre x Base",
"base": "CL31",
"nombre": "NJOURP",
"taux": null,
"tauxPat": null,
"cnps": true,
"impo": true,
"sens": "GAIN"
},
{
"code": "2119",
"label": "PRIME DE PRECARITE",
"family": "BRUT",
"formula": "Nombre x Base",
"base": "CL21",
"nombre": "NJOURP",
"taux": null,
"tauxPat": null,
"cnps": true,
"impo": true,
"sens": "GAIN"
},
{
"code": "2125",
"label": "PRIME DE QUART",
"family": "BRUT",
"formula": "Montant pris tel quel",
"base": null,
"nombre": null,
"taux": null,
"tauxPat": null,
"cnps": true,
"impo": true,
"sens": "GAIN"
},
{
"code": "2126",
"label": "PRIME DE QUART POSTE",
"family": "BRUT",
"formula": "Nombre x Base",
"base": "CL29",
"nombre": "NJOURP",
"taux": null,
"tauxPat": null,
"cnps": true,
"impo": true,
"sens": "GAIN"
},
{
"code": "2127",
"label": "PRIME DE RENDEMENT",
"family": "BRUT",
"formula": "Nombre x Base",
"base": "CL06",
"nombre": "NJOURP",
"taux": null,
"tauxPat": null,
"cnps": true,
"impo": true,
"sens": "GAIN"
},
{
"code": "2128",
"label": "PRIME DE RESPONSABILITE",
"family": "BRUT",
"formula": "Nombre x Base",
"base": "CL19",
"nombre": "NJOURP",
"taux": null,
"tauxPat": null,
"cnps": true,
"impo": true,
"sens": "GAIN"
},
{
"code": "2129",
"label": "PRIME DE SALISSURE",
"family": "BRUT",
"formula": "Nombre x Base",
"base": "CL26",
"nombre": "NJOURP",
"taux": null,
"tauxPat": null,
"cnps": true,
"impo": true,
"sens": "GAIN"
},
{
"code": "2130",
"label": "PRIME DE SECURITE",
"family": "BRUT",
"formula": "Nombre x Base",
"base": "CL13",
"nombre": "NJOUTRAP",
"taux": null,
"tauxPat": null,
"cnps": true,
"impo": true,
"sens": "GAIN"
},
{
"code": "2131",
"label": "PRIME DE TECHNICITE",
"family": "BRUT",
"formula": "Nombre x Base",
"base": "CL24",
"nombre": "NJOUTRAP",
"taux": null,
"tauxPat": null,
"cnps": true,
"impo": true,
"sens": "GAIN"
},
{
"code": "2132",
"label": "PRIME DE TOURNEE",
"family": "BRUT",
"formula": "Nombre x Base",
"base": "CL20",
"nombre": "NJOURP",
"taux": null,
"tauxPat": null,
"cnps": true,
"impo": true,
"sens": "GAIN"
},
{
"code": "2134",
"label": "PRIME D'ELECTRICITE",
"family": "BRUT",
"formula": "Nombre x Base",
"base": "CL28",
"nombre": null,
"taux": null,
"tauxPat": null,
"cnps": true,
"impo": true,
"sens": "GAIN"
},
{
"code": "2137",
"label": "PRIME D'EXPATRIATION",
"family": "BRUT",
"formula": "Nombre x Base",
"base": "CL17",
"nombre": "NJOURP",
"taux": null,
"tauxPat": null,
"cnps": true,
"impo": true,
"sens": "GAIN"
},
{
"code": "2139",
"label": "PRIME D'INTERESSEMENT",
"family": "BRUT",
"formula": "Montant pris tel quel",
"base": null,
"nombre": null,
"taux": null,
"tauxPat": null,
"cnps": true,
"impo": true,
"sens": "GAIN"
},
{
"code": "2140",
"label": "PRIME D'OBJECTIF",
"family": "BRUT",
"formula": "Montant pris tel quel",
"base": null,
"nombre": null,
"taux": null,
"tauxPat": null,
"cnps": true,
"impo": true,
"sens": "GAIN"
},
{
"code": "2141",
"label": "PRIME D'HABILLEMENT",
"family": "BRUT",
"formula": "Nombre x Base",
"base": null,
"nombre": "NJOUTRAP",
"taux": null,
"tauxPat": null,
"cnps": true,
"impo": true,
"sens": "GAIN"
},
{
"code": "2142",
"label": "PRIME EXEPTIONNELLE",
"family": "BRUT",
"formula": "Nombre x Base",
"base": "CL14",
"nombre": "NJOURP",
"taux": null,
"tauxPat": null,
"cnps": true,
"impo": true,
"sens": "GAIN"
},
{
"code": "2143",
"label": "PRIME SPECIALE",
"family": "BRUT",
"formula": "Nombre x Base",
"base": "CL14",
"nombre": "NJOURP",
"taux": null,
"tauxPat": null,
"cnps": true,
"impo": true,
"sens": "GAIN"
},
{
"code": "2144",
"label": "PRIME SPECIALE NT",
"family": "BRUT",
"formula": "Nombre x Base",
"base": null,
"nombre": null,
"taux": null,
"tauxPat": null,
"cnps": true,
"impo": true,
"sens": "GAIN"
},
{
"code": "2145",
"label": "INDEMNITE DE TELEPHONE",
"family": "BRUT",
"formula": "Nombre x Base",
"base": "CL23",
"nombre": null,
"taux": null,
"tauxPat": null,
"cnps": true,
"impo": true,
"sens": "GAIN"
},
{
"code": "2146",
"label": "QUOTE PART ASSURANCE",
"family": "BRUT",
"formula": "Montant pris tel quel",
"base": null,
"nombre": null,
"taux": null,
"tauxPat": null,
"cnps": false,
"impo": true,
"sens": "GAIN"
},
{
"code": "2148",
"label": "QUOTE PART TELEPHONE",
"family": "BRUT",
"formula": "Montant pris tel quel",
"base": null,
"nombre": null,
"taux": null,
"tauxPat": null,
"cnps": false,
"impo": true,
"sens": "GAIN"
},
{
"code": "2501",
"label": "TRANSPORT COLGATE",
"family": "BRUT",
"formula": "Nombre x Base",
"base": null,
"nombre": "NJOUTRAP",
"taux": null,
"tauxPat": null,
"cnps": false,
"impo": true,
"sens": "GAIN"
},
{
"code": "2504",
"label": "ALLOCATION PRODUIT PETROLIER",
"family": "BRUT",
"formula": "Nombre x Base",
"base": null,
"nombre": "NJOUTRAP",
"taux": null,
"tauxPat": null,
"cnps": true,
"impo": true,
"sens": "GAIN"
},
{
"code": "2506",
"label": "RATION",
"family": "BRUT",
"formula": "Nombre x Base",
"base": "CL30",
"nombre": "NJOUNUITR",
"taux": null,
"tauxPat": null,
"cnps": true,
"impo": true,
"sens": "GAIN"
},
{
"code": "2508",
"label": "RAPPEL SALAIRE NON IMPOSABLE",
"family": "BRUT",
"formula": "Montant pris tel quel",
"base": null,
"nombre": null,
"taux": null,
"tauxPat": null,
"cnps": false,
"impo": false,
"sens": "GAIN"
},
{
"code": "2509",
"label": "REMBOURSEMENT ASSURANCE",
"family": "BRUT",
"formula": "Montant pris tel quel",
"base": null,
"nombre": null,
"taux": null,
"tauxPat": null,
"cnps": false,
"impo": false,
"sens": "GAIN"
},
{
"code": "2510",
"label": "RENDEMENT NT",
"family": "BRUT",
"formula": "Nombre x Base",
"base": "CL06",
"nombre": "NJOURP",
"taux": null,
"tauxPat": null,
"cnps": true,
"impo": true,
"sens": "GAIN"
},
{
"code": "2511",
"label": "BONUS",
"family": "BRUT",
"formula": "Montant pris tel quel",
"base": null,
"nombre": null,
"taux": null,
"tauxPat": null,
"cnps": true,
"impo": true,
"sens": "GAIN"
},
{
"code": "2512",
"label": "RECUPERATION",
"family": "BRUT",
"formula": "Nombre x Base",
"base": "SALJOURN",
"nombre": "NJOUTRAP",
"taux": null,
"tauxPat": null,
"cnps": true,
"impo": true,
"sens": "GAIN"
},
{
"code": "2514",
"label": "13 éme MOIS",
"family": "BRUT",
"formula": "Nombre x Base",
"base": null,
"nombre": "NJOUTRAP",
"taux": null,
"tauxPat": null,
"cnps": true,
"impo": true,
"sens": "GAIN"
},
{
"code": "2516",
"label": "FRAIS MEDICAUX",
"family": "BRUT",
"formula": "Montant pris tel quel",
"base": null,
"nombre": null,
"taux": null,
"tauxPat": null,
"cnps": false,
"impo": false,
"sens": "GAIN"
},
{
"code": "2517",
"label": "GRATIFICATION",
"family": "BRUT",
"formula": "Nombre x Base",
"base": null,
"nombre": "NJOUTRAP",
"taux": null,
"tauxPat": null,
"cnps": true,
"impo": true,
"sens": "GAIN"
},
{
"code": "2520",
"label": "PRIME ZODIAC",
"family": "BRUT",
"formula": "Nombre x Base",
"base": "CL09",
"nombre": "NJOUTRAP",
"taux": null,
"tauxPat": null,
"cnps": true,
"impo": true,
"sens": "GAIN"
},
{
"code": "3004",
"label": "PRIME DE MER SP MI OVER",
"family": "BRUT",
"formula": "Nombre x Base",
"base": null,
"nombre": null,
"taux": null,
"tauxPat": null,
"cnps": true,
"impo": true,
"sens": "GAIN"
},
{
"code": "3010",
"label": "PRIME SALISSURE",
"family": "BRUT",
"formula": "Nombre x Base",
"base": "CL26",
"nombre": "NJOURP",
"taux": null,
"tauxPat": null,
"cnps": true,
"impo": true,
"sens": "GAIN"
},
{
"code": "3012",
"label": "PRIME DE SECURITE",
"family": "BRUT",
"formula": "Nombre x Base",
"base": "CL13",
"nombre": "NJOURP",
"taux": null,
"tauxPat": null,
"cnps": true,
"impo": true,
"sens": "GAIN"
},
{
"code": "3500",
"label": "IDEMNITE DE REMPLACEMENT",
"family": "BRUT",
"formula": "Montant pris tel quel",
"base": null,
"nombre": null,
"taux": null,
"tauxPat": null,
"cnps": true,
"impo": true,
"sens": "GAIN"
},
{
"code": "3501",
"label": "IDEMNITE DE SUGGESTION",
"family": "BRUT",
"formula": "Nombre x Base",
"base": null,
"nombre": "NJOUTRAP",
"taux": null,
"tauxPat": null,
"cnps": true,
"impo": true,
"sens": "GAIN"
},
{
"code": "3502",
"label": "IND FIN DE CARRIERE",
"family": "BRUT",
"formula": "Nombre x Base x Taux",
"base": null,
"nombre": null,
"taux": null,
"tauxPat": null,
"cnps": true,
"impo": true,
"sens": "GAIN"
},
{
"code": "3503",
"label": "INDEM LICENCIEMENT",
"family": "BRUT",
"formula": "Montant pris tel quel",
"base": null,
"nombre": null,
"taux": null,
"tauxPat": null,
"cnps": true,
"impo": true,
"sens": "GAIN"
},
{
"code": "3504",
"label": "INDEMNITE  D INTERIM",
"family": "BRUT",
"formula": "Nombre x Base",
"base": "CL29",
"nombre": "NJOURP",
"taux": null,
"tauxPat": null,
"cnps": true,
"impo": true,
"sens": "GAIN"
},
{
"code": "3505",
"label": "INDEMNITE  DE FONCTION",
"family": "BRUT",
"formula": "Nombre x Base",
"base": "CL22",
"nombre": "NJOURP",
"taux": null,
"tauxPat": null,
"cnps": true,
"impo": true,
"sens": "GAIN"
},
{
"code": "3506",
"label": "INDEMNITE  D'USAGE VEHICULE",
"family": "BRUT",
"formula": "Montant pris tel quel",
"base": null,
"nombre": null,
"taux": null,
"tauxPat": null,
"cnps": true,
"impo": true,
"sens": "GAIN"
},
{
"code": "3507",
"label": "INDEMNITE DE DECES",
"family": "BRUT",
"formula": "Nombre x Base",
"base": null,
"nombre": "NJOUTRAP",
"taux": null,
"tauxPat": null,
"cnps": true,
"impo": true,
"sens": "GAIN"
},
{
"code": "3508",
"label": "INDEMNITE DE DEPLACEMENT",
"family": "BRUT",
"formula": "Nombre x Base",
"base": "CL04",
"nombre": "NJOURP",
"taux": null,
"tauxPat": null,
"cnps": true,
"impo": true,
"sens": "GAIN"
},
{
"code": "3509",
"label": "PRIME ASSURANCE",
"family": "BRUT",
"formula": "Nombre x Base",
"base": "CL22",
"nombre": "NJOURP",
"taux": null,
"tauxPat": null,
"cnps": true,
"impo": true,
"sens": "GAIN"
},
{
"code": "3510",
"label": "INDEMNITE DE LOGEMENT",
"family": "BRUT",
"formula": "Nombre x Base",
"base": "CL02",
"nombre": "NJOURP",
"taux": null,
"tauxPat": null,
"cnps": true,
"impo": true,
"sens": "GAIN"
},
{
"code": "3511",
"label": "INDEMNITE DE NOURRITURE",
"family": "BRUT",
"formula": "Nombre x Base",
"base": "CL25",
"nombre": "NJOUTRAP",
"taux": null,
"tauxPat": null,
"cnps": true,
"impo": true,
"sens": "GAIN"
},
{
"code": "3512",
"label": "INDEMNITE DE REPRESENTATION",
"family": "BRUT",
"formula": "Nombre x Base",
"base": "CL03",
"nombre": "NJOURP",
"taux": null,
"tauxPat": null,
"cnps": true,
"impo": true,
"sens": "GAIN"
},
{
"code": "3513",
"label": "INDEMNITE DE TRANSPORT",
"family": "BRUT",
"formula": "Nombre x Base",
"base": "CL01",
"nombre": "NJOUTRAP",
"taux": null,
"tauxPat": null,
"cnps": false,
"impo": true,
"sens": "GAIN"
},
{
"code": "3514",
"label": "INDEMNITE DE DOCUMENTATION",
"family": "BRUT",
"formula": "Nombre x Base",
"base": "CL08",
"nombre": "NJOURP",
"taux": null,
"tauxPat": null,
"cnps": true,
"impo": true,
"sens": "GAIN"
},
{
"code": "3515",
"label": "INDEMNITE ENTR. VEHICULE",
"family": "BRUT",
"formula": "Montant pris tel quel",
"base": null,
"nombre": null,
"taux": null,
"tauxPat": null,
"cnps": true,
"impo": true,
"sens": "GAIN"
},
{
"code": "3516",
"label": "INDEMNITE LICENCIEMENT",
"family": "BRUT",
"formula": "Base x Taux",
"base": null,
"nombre": null,
"taux": null,
"tauxPat": null,
"cnps": true,
"impo": true,
"sens": "GAIN"
},
{
"code": "3517",
"label": "PREAVIS",
"family": "BRUT",
"formula": "Nombre x Base x Taux",
"base": "BRUT",
"nombre": null,
"taux": null,
"tauxPat": null,
"cnps": true,
"impo": true,
"sens": "GAIN"
},
{
"code": "3518",
"label": "PREAVIS 2",
"family": "BRUT",
"formula": "Montant pris tel quel",
"base": null,
"nombre": null,
"taux": null,
"tauxPat": null,
"cnps": true,
"impo": true,
"sens": "GAIN"
},
{
"code": "3520",
"label": "INDEMNITE DE LOGEMENT",
"family": "BRUT",
"formula": "Nombre x Base",
"base": "CL02",
"nombre": "NJOURP",
"taux": null,
"tauxPat": null,
"cnps": true,
"impo": true,
"sens": "GAIN"
},
{
"code": "3700",
"label": "CONGES MENSUELS SURF",
"family": "BRUT",
"formula": "Nombre x Base",
"base": "CONGES",
"nombre": "NJOUTRAP",
"taux": null,
"tauxPat": null,
"cnps": true,
"impo": true,
"sens": "GAIN"
},
{
"code": "3701",
"label": "CONGES MENSUELS",
"family": "BRUT",
"formula": "Nombre x Base",
"base": null,
"nombre": "NJOUTRAP",
"taux": null,
"tauxPat": null,
"cnps": true,
"impo": true,
"sens": "GAIN"
},
{
"code": "3702",
"label": "CONGES ANNUELS",
"family": "BRUT",
"formula": "Montant pris tel quel",
"base": null,
"nombre": null,
"taux": null,
"tauxPat": null,
"cnps": true,
"impo": true,
"sens": "GAIN"
},
{
"code": "3703",
"label": "CONGES MENSUEL",
"family": "BRUT",
"formula": "Nombre x Base",
"base": "BASEC",
"nombre": null,
"taux": null,
"tauxPat": null,
"cnps": true,
"impo": true,
"sens": "GAIN"
},
{
"code": "3704",
"label": "CONGES CT",
"family": "BRUT",
"formula": "Nombre x Base",
"base": "BASECCAD",
"nombre": "NJOUTRAP",
"taux": null,
"tauxPat": null,
"cnps": true,
"impo": true,
"sens": "GAIN"
},
{
"code": "3705",
"label": "CONGE  MENSUEL SURFER",
"family": "BRUT",
"formula": "Nombre x Base",
"base": null,
"nombre": "NJOUTRAP",
"taux": null,
"tauxPat": null,
"cnps": true,
"impo": true,
"sens": "GAIN"
},
{
"code": "3706",
"label": "CONGES MENSUEL",
"family": "BRUT",
"formula": "Nombre x Base",
"base": "BASEC",
"nombre": null,
"taux": null,
"tauxPat": null,
"cnps": true,
"impo": true,
"sens": "GAIN"
},
{
"code": "3707",
"label": "RAPPEL CONGE",
"family": "BRUT",
"formula": "Montant pris tel quel",
"base": null,
"nombre": null,
"taux": null,
"tauxPat": null,
"cnps": true,
"impo": true,
"sens": "GAIN"
},
{
"code": "3708",
"label": "CONGES MENSUEL B",
"family": "BRUT",
"formula": "Nombre x Base",
"base": "BASECBAN",
"nombre": null,
"taux": null,
"tauxPat": null,
"cnps": true,
"impo": true,
"sens": "GAIN"
},
{
"code": "3709",
"label": "CONGE MENSUEL",
"family": "BRUT",
"formula": "Nombre x Base",
"base": "BASEC",
"nombre": null,
"taux": null,
"tauxPat": null,
"cnps": true,
"impo": true,
"sens": "GAIN"
},
{
"code": "3710",
"label": "RAPPEL CONGE N",
"family": "BRUT",
"formula": "Montant pris tel quel",
"base": null,
"nombre": null,
"taux": null,
"tauxPat": null,
"cnps": true,
"impo": true,
"sens": "GAIN"
},
{
"code": "3711",
"label": "CONGE ANNUEL",
"family": "BRUT",
"formula": "Nombre x Base x Taux",
"base": null,
"nombre": null,
"taux": null,
"tauxPat": null,
"cnps": true,
"impo": true,
"sens": "GAIN"
},
{
"code": "4740",
"label": "PART COTI LGMT",
"family": "BRUT",
"formula": "Montant pris tel quel",
"base": null,
"nombre": null,
"taux": null,
"tauxPat": null,
"cnps": true,
"impo": true,
"sens": "GAIN"
},
{
"code": "4750",
"label": "PART TAXABLE  LOGEMENT",
"family": "BRUT",
"formula": "Montant pris tel quel",
"base": null,
"nombre": null,
"taux": null,
"tauxPat": null,
"cnps": true,
"impo": true,
"sens": "GAIN"
},
{
"code": "5000",
"label": "PENSION VIEILLESSE",
"family": "COTISATION",
"formula": "Base x Taux",
"base": "NETCOTI",
"nombre": null,
"taux": 4.2,
"tauxPat": 4.2,
"cnps": false,
"impo": false,
"sens": "RETENUE"
},
{
"code": "5010",
"label": "ALLOCATIONS FAMILIALES",
"family": "COTISATION",
"formula": "Base x Taux",
"base": "NETCOTI",
"nombre": null,
"taux": null,
"tauxPat": 7.0,
"cnps": false,
"impo": false,
"sens": "PATRONAL"
},
{
"code": "5015",
"label": "IRPP 2",
"family": "COTISATION",
"formula": "Montant pris tel quel",
"base": "NETIMPO",
"nombre": null,
"taux": null,
"tauxPat": null,
"cnps": false,
"impo": false,
"sens": "RETENUE"
},
{
"code": "5020",
"label": "ACCIDENT DE TRAVAIL",
"family": "COTISATION",
"formula": "Base x Taux",
"base": "NETCOT",
"nombre": null,
"taux": null,
"tauxPat": 2.5,
"cnps": false,
"impo": false,
"sens": "PATRONAL"
},
{
"code": "5025",
"label": "IRPP1",
"family": "COTISATION",
"formula": "Montant pris tel quel",
"base": "NETIMPO",
"nombre": null,
"taux": null,
"tauxPat": null,
"cnps": false,
"impo": false,
"sens": "RETENUE"
},
{
"code": "5030",
"label": "IRPP",
"family": "COTISATION",
"formula": "Montant pris tel quel",
"base": "NETIMPO",
"nombre": null,
"taux": null,
"tauxPat": null,
"cnps": false,
"impo": false,
"sens": "RETENUE"
},
{
"code": "5035",
"label": "CAC/IRPP 2",
"family": "COTISATION",
"formula": "Base x Taux",
"base": "CACIRPP",
"nombre": null,
"taux": 10.0,
"tauxPat": null,
"cnps": false,
"impo": false,
"sens": "RETENUE"
},
{
"code": "5040",
"label": "CAC/IRPP",
"family": "COTISATION",
"formula": "Base x Taux",
"base": "CACIRPP",
"nombre": null,
"taux": 10.0,
"tauxPat": null,
"cnps": false,
"impo": false,
"sens": "RETENUE"
},
{
"code": "5045",
"label": "CAC/IRPP 1",
"family": "COTISATION",
"formula": "Base x Taux",
"base": "CACIRPP1",
"nombre": null,
"taux": 10.0,
"tauxPat": null,
"cnps": false,
"impo": false,
"sens": "RETENUE"
},
{
"code": "5050",
"label": "CREDIT FONCIER",
"family": "COTISATION",
"formula": "Base x Taux",
"base": "BASECF",
"nombre": null,
"taux": 1.0,
"tauxPat": null,
"cnps": false,
"impo": false,
"sens": "RETENUE"
},
{
"code": "5060",
"label": "CREDIT FONCIER PATR.",
"family": "COTISATION",
"formula": "Base x Taux",
"base": "BRUT",
"nombre": null,
"taux": null,
"tauxPat": 1.5,
"cnps": false,
"impo": false,
"sens": "PATRONAL"
},
{
"code": "5070",
"label": "FNE",
"family": "COTISATION",
"formula": "Base x Taux",
"base": "BRUT",
"nombre": null,
"taux": null,
"tauxPat": 1.0,
"cnps": false,
"impo": false,
"sens": "PATRONAL"
},
{
"code": "5080",
"label": "REDEVANCE CRTV",
"family": "COTISATION",
"formula": "Montant pris tel quel",
"base": "NETIMPO",
"nombre": null,
"taux": null,
"tauxPat": null,
"cnps": false,
"impo": false,
"sens": "RETENUE"
},
{
"code": "5090",
"label": "TAXE COMMUNALE",
"family": "COTISATION",
"formula": "Montant pris tel quel",
"base": "NETIMPO",
"nombre": null,
"taux": null,
"tauxPat": null,
"cnps": false,
"impo": false,
"sens": "RETENUE"
},
{
"code": "5095",
"label": "COTISATION SYNDICALE",
"family": "COTISATION",
"formula": "Base x Taux",
"base": "SALBASE",
"nombre": null,
"taux": 1.0,
"tauxPat": null,
"cnps": false,
"impo": false,
"sens": "RETENUE"
},
{
"code": "5200",
"label": "PENSION VIEILLESSE",
"family": "COTISATION",
"formula": "Montant pris tel quel",
"base": "BRUT",
"nombre": null,
"taux": null,
"tauxPat": null,
"cnps": false,
"impo": false,
"sens": "RETENUE"
},
{
"code": "5210",
"label": "ALLOCATIONS FAMILIALES",
"family": "COTISATION",
"formula": "Montant pris tel quel",
"base": "BRUT",
"nombre": null,
"taux": null,
"tauxPat": null,
"cnps": false,
"impo": false,
"sens": "PATRONAL"
},
{
"code": "5220",
"label": "IRPP",
"family": "COTISATION",
"formula": "Montant pris tel quel",
"base": "NETIMPO",
"nombre": null,
"taux": null,
"tauxPat": null,
"cnps": false,
"impo": false,
"sens": "RETENUE"
},
{
"code": "5230",
"label": "CAC/IRPP",
"family": "COTISATION",
"formula": "Montant pris tel quel",
"base": "BRUT",
"nombre": null,
"taux": null,
"tauxPat": null,
"cnps": false,
"impo": false,
"sens": "RETENUE"
},
{
"code": "5240",
"label": "CREDIT FONCIER",
"family": "COTISATION",
"formula": "Montant pris tel quel",
"base": "BRUT",
"nombre": null,
"taux": null,
"tauxPat": null,
"cnps": false,
"impo": false,
"sens": "RETENUE"
},
{
"code": "5245",
"label": "CREDIT FONCIER PATR.",
"family": "COTISATION",
"formula": "Montant pris tel quel",
"base": "BRUT",
"nombre": null,
"taux": null,
"tauxPat": null,
"cnps": false,
"impo": false,
"sens": "PATRONAL"
},
{
"code": "5250",
"label": "FNE",
"family": "COTISATION",
"formula": "Montant pris tel quel",
"base": "BRUT",
"nombre": null,
"taux": null,
"tauxPat": null,
"cnps": false,
"impo": false,
"sens": "PATRONAL"
},
{
"code": "5260",
"label": "REDEVANCE CRTV",
"family": "COTISATION",
"formula": "Montant pris tel quel",
"base": "NETIMPO",
"nombre": null,
"taux": null,
"tauxPat": null,
"cnps": false,
"impo": false,
"sens": "RETENUE"
},
{
"code": "5270",
"label": "TAXE COMMUNALE",
"family": "COTISATION",
"formula": "Montant pris tel quel",
"base": "NETIMPO",
"nombre": null,
"taux": null,
"tauxPat": null,
"cnps": false,
"impo": false,
"sens": "RETENUE"
},
{
"code": "7000",
"label": "ACOMPTE SUR SALAIRE",
"family": "NON_SOUMISE",
"formula": "Montant pris tel quel",
"base": null,
"nombre": null,
"taux": null,
"tauxPat": null,
"cnps": false,
"impo": false,
"sens": "GAIN"
},
{
"code": "7010",
"label": "AVANCE SUR SALAIRE",
"family": "NON_SOUMISE",
"formula": "Montant pris tel quel",
"base": null,
"nombre": null,
"taux": null,
"tauxPat": null,
"cnps": false,
"impo": false,
"sens": "GAIN"
},
{
"code": "7020",
"label": "SALAIRE DEJA PAYE/ VIRE",
"family": "NON_SOUMISE",
"formula": "Montant pris tel quel",
"base": null,
"nombre": null,
"taux": null,
"tauxPat": null,
"cnps": false,
"impo": false,
"sens": "GAIN"
},
{
"code": "7025",
"label": "TROP PERCU",
"family": "NON_SOUMISE",
"formula": "Montant pris tel quel",
"base": null,
"nombre": null,
"taux": null,
"tauxPat": null,
"cnps": false,
"impo": false,
"sens": "GAIN"
},
{
"code": "7030",
"label": "RETENUES DIVERSES",
"family": "NON_SOUMISE",
"formula": "Montant pris tel quel",
"base": null,
"nombre": null,
"taux": null,
"tauxPat": null,
"cnps": false,
"impo": false,
"sens": "GAIN"
},
{
"code": "7035",
"label": "PREAVIS RETENU",
"family": "NON_SOUMISE",
"formula": "Montant pris tel quel",
"base": null,
"nombre": null,
"taux": null,
"tauxPat": null,
"cnps": false,
"impo": false,
"sens": "GAIN"
},
{
"code": "7050",
"label": "RETENUE MUPES",
"family": "NON_SOUMISE",
"formula": "Montant pris tel quel",
"base": null,
"nombre": null,
"taux": null,
"tauxPat": null,
"cnps": false,
"impo": false,
"sens": "GAIN"
},
{
"code": "7150",
"label": "REMBOURSEMENT BANCAIRE",
"family": "NON_SOUMISE",
"formula": "Montant pris tel quel",
"base": null,
"nombre": null,
"taux": null,
"tauxPat": null,
"cnps": false,
"impo": false,
"sens": "GAIN"
},
{
"code": "7490",
"label": "REMBORSEMENT CREDIT 1",
"family": "NON_SOUMISE",
"formula": "Montant pris tel quel",
"base": null,
"nombre": null,
"taux": null,
"tauxPat": null,
"cnps": false,
"impo": false,
"sens": "GAIN"
},
{
"code": "7500",
"label": "REMBORSEMENT CREDIT 2",
"family": "NON_SOUMISE",
"formula": "Montant pris tel quel",
"base": null,
"nombre": null,
"taux": null,
"tauxPat": null,
"cnps": false,
"impo": false,
"sens": "GAIN"
},
{
"code": "7510",
"label": "REMBORSEMENT CREDIT 3",
"family": "NON_SOUMISE",
"formula": "Montant pris tel quel",
"base": null,
"nombre": null,
"taux": null,
"tauxPat": null,
"cnps": false,
"impo": false,
"sens": "GAIN"
},
{
"code": "7520",
"label": "REMBORSEMENT CREDIT 4",
"family": "NON_SOUMISE",
"formula": "Montant pris tel quel",
"base": null,
"nombre": null,
"taux": null,
"tauxPat": null,
"cnps": false,
"impo": false,
"sens": "GAIN"
},
{
"code": "7540",
"label": "QUOTE PART TELEPHONE",
"family": "NON_SOUMISE",
"formula": "Montant pris tel quel",
"base": null,
"nombre": null,
"taux": null,
"tauxPat": null,
"cnps": false,
"impo": false,
"sens": "GAIN"
},
{
"code": "7890",
"label": "ASSURANCE",
"family": "NON_SOUMISE",
"formula": "Montant pris tel quel",
"base": null,
"nombre": null,
"taux": null,
"tauxPat": null,
"cnps": false,
"impo": false,
"sens": "GAIN"
},
{
"code": "7900",
"label": "BON DE PHARMACIE",
"family": "NON_SOUMISE",
"formula": "Montant pris tel quel",
"base": null,
"nombre": null,
"taux": null,
"tauxPat": null,
"cnps": false,
"impo": false,
"sens": "GAIN"
},
{
"code": "7910",
"label": "FRAIS MEDICAUX",
"family": "NON_SOUMISE",
"formula": "Montant pris tel quel",
"base": null,
"nombre": null,
"taux": null,
"tauxPat": null,
"cnps": false,
"impo": false,
"sens": "GAIN"
}
];
